[project]
name = "ipl-2008-2022"
version = "0.1.0"
description = "Playing with IPL data to understand SQL queries"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.1",
]
